routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('account','AccountController');
Route::resource('acctype','ACCTypeController');
Route::resource('staff','StaffController');
ROute::get('account/calculaterate','AccountController@CalculateRate')->name('account.calculaterate');

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/ACCTypeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;

class ACCTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // select * from ACCType
        $acctype = DB::table('ACCType')->get();
        return view('acctype.index', compact('acctype'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('acctype.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'Type_No' => 'required',
            'Type_Name' => 'required',
            'Rate' => 'required'
        ]);

        DB::table('ACCType')->insert([

            'Type_No' => $request->Type_No,
            'Type_Name' => $request->Type_Name,
            'DateBegin' => now(),
            'DateEnd' => now(),
            'Rate' => $request->Rate

        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/acctype/create.blade.php
@extends('acctype.layout')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div>
                        ประเภทบัญชี
                    </div>
                    <form action="{{ route('acctype.store') }}" method="POST">
                        @csrf
                        @method("POST")
                        <table border=1>
                            <tr>
                                <td>ชนิดบัญชี</td>
                                <td><input type="text" name="Type_No"></td>
                            </tr>
                            <tr>
                                <td>ชื่อประเภท</td>
                                <td><input type="text" name="Type_Name"></td>
                            </tr>
                            <tr>
                                <td>วันที่เริ่มต้น</td>
                                <td><input type="text" name="DateBegin"></td>
                            </tr>
                            <tr>
                                <td>วันที่สิ้นสุด</td>
                                <td><input type="text" name="DateEnd"></td>
                            </tr>
                            <tr>
                                <td>ดอกเบี้ย</td>
                                <td><input type="text" name="Rate"></td>
                            </tr>
                            <tr>
                                <td colspan=2>
                                    <button type="submit" class="btn btn-success">บันทึกข้อมูล</button>
                                    <button type="reset" class="btn btn-danger">ยกเลิก</button>
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div> @endsection

resources/views/acctype/index.blade.php
@extends('acctype.layout')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div>
                        <a class="btn btn-primary" href="{{ route('acctype.create') }}">เพิ่ม</a>
                    </div>
                    <table border=1>
                        <tr align="center">
                            <td>ชนิดบัญชี</td>
                            <td>ชื่อประเภท</td>
                            <td>วันที่เริ่มต้น</td>
                            <td>วันที่สิ้นสุด</td>
                            <td>ดอกเบี้ย</td>
                            <td colspan=2>การดำเนินงาน</td>
                        </tr>
                        @foreach($acctype as $acct)
                        <tr>
                            <td align="center">{{ $acct->Type_No }}</td>
                            <td>{{ $acct->Type_Name }}</td>
                            <td>{{ $acct->DateBegin }}</td>
                            <td>{{ $acct->DateEnd }}</td>
                            <td align="center">{{ $acct->Rate }}</td>
                            <td>
                                Edit
                                Delete
                            </td>
                        </tr>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/acctype/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel 6 CRUD Application</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>
<div>
    <div class="container">
        @yield('content')
    </div>
</div>
   
</body>
</html>