routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('account','AccountController');
Route::resource('acctype','ACCTypeController');
Route::resource('staff','StaffController');
ROute::get('account/calculaterate','AccountController@CalculateRate')->name('account.calculaterate');

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/StaffController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;

class StaffController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // select * from Account
        // $account = DB::table('Account')->get();
        // return view('account.index', compact('account'));
        $staff = DB::table('Staff')->get();
        return view('staff.index', compact('staff'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('staff.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([

            'Staff_No' => 'required',
            'Staff_Name' => 'required',
            'Staff_Surname' => 'required',
            'Staff_Address' => 'required',
            'Staff_Email' => 'required',
            'Staff_Phone' => 'required'
            
        ]);

        DB::table('Staff')->insert([

            'Staff_No' => $request->Staff_No,
            'Staff_Name' => $request->Staff_Name,
            'Staff_Surname' => $request->Staff_Surname,
            'Staff_Address' => $request->Staff_Address,
            'Staff_Email' => $request->Staff_Email,
            'Staff_Phone' => $request->Staff_Phone
           

        ]);
        return redirect('staff/');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    public function CalculateRate()
    {
        // $accounts = DB::table('Account')->get();
        // foreach ($accounts as $account)
        // {
        //     DB::select('call CalInterestUPD(?)',array($account->ACC_No));
        // }
        // redirect('account');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // $account = DB::table('Account')->where('ACC_No','=',$id)->get();
        // return view('account.edit',compact('account'));
        $staff = DB::table('Staff')->where('Staff_No','=',$id)->get();
        return view('staff.edit',compact('staff'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([

            'Staff_No' => 'required',
            'Staff_Name' => 'required',
            'Staff_Surname' => 'required',
            'Staff_Address' => 'required',
            'Staff_Email' => 'required',
            'Staff_Phone' => 'required'
            
        ]);

        DB::table('Staff')->where('Staff_No','=',$id)->update([

            'Staff_No' => $request->Staff_No,
            'Staff_Name' => $request->Staff_Name,
            'Staff_Surname' => $request->Staff_Surname,
            'Staff_Address' => $request->Staff_Address,
            'Staff_Email' => $request->Staff_Email,
            'Staff_Phone' => $request->Staff_Phone
        ]);
        
        return redirect('staff');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // DB::table("Account")->where('ACC_No','=',$id)->delete();
        // return redirect('account');
        DB::table("Staff")->where('Staff_No','=',$id)->delete();
        return redirect('staff');
    }
}

resources/views/staff/create.blade.php
@extends('staff.layout')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div>
                        ADD STAFF
                    </div>
                    <form action="{{ route('staff.store') }}" method="POST">
                        @csrf
                        @method("POST")
                        <table border="1">
                            <tr>
                                <td>เลขประจำตัว</td>
                                <td><input type="text" name="Staff_No"></td>
                            </tr>
                            <tr>
                                <td>ชื่อ</td>
                                <td><input type="text" name="Staff_Name"></td>
                            </tr>
                            <tr>
                                <td>นามสกุล</td>
                                <td><input type="text" name="Staff_Surname"></td>
                            </tr>
                            <tr>
                                <td>ที่อยู่</td>
                                <td><input type="text" name="Staff_Address"></td>
                            </tr>
                            <tr>
                                <td>อีเมล์</td>
                                <td><input type="text" name="Staff_Email"></td>
                            </tr>
                            <tr>
                                <td>เบอร์โทรศัพท์</td>
                                <td><input type="text" name="Staff_Phone"></td>
                            </tr>

                            <tr>
                                <td colspan=2>
                                    <button type="submit" class="btn btn-success">บันทึกข้อมูล</button>
                                    <button type="reset" class="btn btn-danger">ยกเลิก</button>
                                </td>
                            </tr>

                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/staff/edit.blade.php
@extends('staff.layout')

@section('content')
@foreach($staff as $sta)
@endforeach

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div>
                        แก้ไขข้อมลู
                    </div>
                    <form action="{{ route('staff.update',$sta->Staff_No) }}" method="POST">
                        @csrf
                        @method("PUT")
                        <table border="1">
                        <tr>
                                <td>เลขประจำตัว</td>
                                <td><input type="text" name="Staff_No" value="{{ $sta->Staff_No }}" readonly></td>
                            </tr>
                            <tr>
                                <td>ชื่อ</td>
                                <td><input type="text" name="Staff_Name" value="{{ $sta->Staff_Name }}"></td>
                            </tr>
                            <tr>
                                <td>นามสกุล</td>
                                <td><input type="text" name="Staff_Surname" value="{{ $sta->Staff_Surname }}"></td>
                            </tr>
                            <tr>
                                <td>ที่อยู่</td>
                                <td><input type="text" name="Staff_Address" value="{{ $sta->Staff_Address }}"></td>
                            </tr>
                            <tr>
                                <td>อีเมล์</td>
                                <td><input type="text" name="Staff_Email" value="{{ $sta->Staff_Email }}"></td>
                            </tr>
                            <tr>
                                <td>เบอร์โทรศัพท์</td>
                                <td><input type="text" name="Staff_Phone" value="{{ $sta->Staff_Phone }}"></td>
                            </tr>
                                <td colspan=2>
                                <button type="submit" class="btn btn-success">บันทึกข้อมูล</button>
                                    <button type="reset" class="btn btn-danger">ยกเลิก</button>
                                </td>
                            </tr>

                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/staff/index.blade.php
@extends('staff.layout')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div>
                        <a class="btn btn-primary" href="{{ route('staff.create') }}">เพิ่ม</a>
                        <!-- <a class="btn btn-success" href=" ">โอนเงิน</a>
                        <a class="btn btn-danger" href="{{ route('account.calculaterate') }}">คำนวณดอกเบี้ย</a> -->
                    </div>
                    <table border=1>
                        <tr>
                            <td>เลขประจำตัว</td>
                            <td>ชื่อ</td>
                            <td>นามสกุล</td>
                            <td>ที่อยู่</td>
                            <td>อีเมล์</td>
                            <td>เบอร์โทรศัพท์</td>
                            <td colspan=2>การดำเนินงาน</td>
                        </tr>
                        @foreach($staff as $sta)
                        <tr>
                            <td>{{ $sta->Staff_No }}</td>
                            <td>{{ $sta->Staff_Name }}</td>
                            <td>{{ $sta->Staff_Surname }}</td>
                            <td>{{ $sta->Staff_Address }}</td>
                            <td>{{ $sta->Staff_Email }}</td>
                            <td>{{ $sta->Staff_Phone }}</td>
                            <td>
                                <form action="{{ route('staff.destroy',$sta->Staff_No) }}" method="POST">
                                    <a class="btn btn-primary" href="{{ route('staff.edit',$sta->Staff_No) }}">Edit</a>
                                    @csrf
                                    @method("DELETE")
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/staff/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel 6 CRUD Application</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>
<div>
    <div class="container">
        @yield('content')
    </div>
</div>
   
</body>
</html>